name: Continuous integration

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Run make format
      uses: ./.github/actions/ci
      with:
        what: format
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Run make lint
      uses: ./.github/actions/ci
      with:
        what: lint
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Run make shellcheck
      uses: ./.github/actions/ci
      with:
        what: shellcheck
  build-clang:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Build with clang
      uses: ./.github/actions/ci
      with:
        what: clang
  build-gcc:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Build with gcc
      uses: ./.github/actions/ci
      with:
        what: gcc
